name: connect
version: 1.0.0-alpha.2
author: Christoph Grundmann <christoph.grundmann@gmail.com>
homepage: https://github.com/MasterLinux/Connect
description:
  This library is used for communication between objects.
environment:
  sdk: "1.0.3"
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"

